import type { Metadata, Viewport } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import Script from "next/script";
import ConsentBanner from "@/components/ConsentBanner";
import WebVitals from "@/components/WebVitals";
import "./globals.css";

const sans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

const mono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL("https://microflexfilm.com"),
  title: {
    default: "Microflex Film Corporation | Flexible Packaging. Engineered to Perform.",
    template: "%s — Microflex Film",
  },
  description:
    "Microflex Film Corporation — flexible packaging, printed film, labels, pouches, sachets, stick packs, shrink sleeves, and custom packaging solutions.",
  keywords: [
    "flexible packaging",
    "printed film",
    "rollstock",
    "pouches",
    "stick packs",
    "sachets",
    "labels",
    "shrink sleeves",
    "Microflex Film Corporation",
    "Riverside packaging",
  ],
  icons: {
    icon: [
      { url: "/images/microflex-mark.png", type: "image/png" },
    ],
    apple: [
      { url: "/images/microflex-mark.png", sizes: "180x180", type: "image/png" },
    ],
    shortcut: "/images/microflex-mark.png",
  },
  openGraph: {
    title: "Microflex Film Corporation — Flexible Packaging. Engineered to Perform.",
    description:
      "Flexible packaging, printed film, labels, pouches, sachets, stick packs, shrink sleeves, and custom solutions. SQF certified. Solar powered. Manufactured in the USA.",
    url: "https://microflexfilm.com",
    siteName: "Microflex Film Corporation",
    type: "website",
    // og:image generated dynamically by app/opengraph-image.tsx (1200×630, branded).
  },
  twitter: {
    card: "summary_large_image",
    title: "Microflex Film Corporation",
    description: "Flexible Packaging. Engineered to Perform.",
    // twitter:image generated by app/twitter-image.tsx.
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  themeColor: "#020509",
  colorScheme: "dark",
};

// Tidio live chat. Customer chats route into a Google Chat space via Tidio's
// native Google Chat integration so Randy + team reply directly inside Google
// Chat without switching apps. Loads only when NEXT_PUBLIC_TIDIO_PUBLIC_KEY is
// set to a real public key (alphanumeric, ~10 chars). Placeholder values are
// ignored so the site stays clean until a real key is provisioned.
const TIDIO_PUBLIC_KEY = process.env.NEXT_PUBLIC_TIDIO_PUBLIC_KEY;
const TIDIO_ENABLED = TIDIO_PUBLIC_KEY && /^[a-z0-9]{8,40}$/i.test(TIDIO_PUBLIC_KEY);

// Google Analytics 4 — defaults to the Firebase web app's measurement ID.
const GA_ID = process.env.NEXT_PUBLIC_GA_ID ?? "G-JSN4SZ1J2Z";
// Microsoft Clarity heatmaps/session replay — opt-in via env.
const CLARITY_ID = process.env.NEXT_PUBLIC_CLARITY_ID;

// Sitewide structured data — LocalBusiness for local + industry search.
// TODO: confirm openingHours, add real social/profile URLs to sameAs, and
// fine-tune geo coordinates if needed.
const ORG_JSONLD = {
  "@context": "https://schema.org",
  "@type": ["Organization", "LocalBusiness"],
  "@id": "https://microflexfilm.com/#business",
  name: "Microflex Film Corporation",
  alternateName: "Microflex Film",
  url: "https://microflexfilm.com",
  logo: "https://microflexfilm.com/images/microflex-logo-white.png",
  image: "https://microflexfilm.com/opengraph-image",
  email: "info@microflexfilm.com",
  telephone: "+1-909-360-9066",
  priceRange: "$$",
  description:
    "Flexible packaging manufacturer — printed film, rollstock, pouches, labels, sachets, stick packs, and shrink sleeves. SQF certified, solar powered, manufactured in the USA. Serving Riverside, the Inland Empire, Southern California, and brands nationwide.",
  address: {
    "@type": "PostalAddress",
    streetAddress: "4130 Garner Rd.",
    addressLocality: "Riverside",
    addressRegion: "CA",
    postalCode: "92501",
    addressCountry: "US",
  },
  geo: { "@type": "GeoCoordinates", latitude: 33.9956, longitude: -117.3739 },
  areaServed: [
    { "@type": "City", name: "Riverside" },
    { "@type": "AdministrativeArea", name: "Inland Empire" },
    { "@type": "AdministrativeArea", name: "Southern California" },
    { "@type": "Country", name: "United States" },
  ],
  openingHoursSpecification: [
    {
      "@type": "OpeningHoursSpecification",
      dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
      opens: "08:00",
      closes: "17:00",
    },
  ],
  sameAs: [] as string[],
  knowsAbout: [
    "flexible packaging", "stand-up pouches", "printed rollstock", "shrink sleeves",
    "labels", "stick packs", "sachets", "barrier films", "custom packaging",
  ],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${sans.variable} ${mono.variable}`}>
      <body>
        <a
          href="#top"
          className="sr-only rounded-full px-4 py-2 text-sm font-bold focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[200]"
          style={{ background: "#00d8f2", color: "#001018" }}
        >
          Skip to content
        </a>
        {/* Organization structured data (rendered in SSR HTML for crawlers) */}
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(ORG_JSONLD) }} />
        {children}

        {/* Consent Mode v2 — analytics denied by default until the visitor opts in. */}
        {GA_ID && (
          <>
            <Script id="consent-default" strategy="beforeInteractive">
              {`window.dataLayer=window.dataLayer||[];window.gtag=function(){dataLayer.push(arguments);};gtag('consent','default',{ad_storage:'denied',ad_user_data:'denied',ad_personalization:'denied',analytics_storage:'denied'});gtag('js',new Date());`}
            </Script>
            <Script src={`https://www.googletagmanager.com/gtag/js?id=${GA_ID}`} strategy="afterInteractive" />
            <Script id="ga4" strategy="afterInteractive">
              {`gtag('config','${GA_ID}',{anonymize_ip:true});`}
            </Script>
          </>
        )}
        <ConsentBanner clarityId={CLARITY_ID} />
        <WebVitals />

        {TIDIO_ENABLED && (
          <Script
            id="tidio-chat"
            strategy="afterInteractive"
            src={`//code.tidio.co/${TIDIO_PUBLIC_KEY}.js`}
          />
        )}
      </body>
    </html>
  );
}
